version: "3.8"

services:
  app:
    container_name: huba-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  nginx:
    container_name: huba-nginx
    image: nginx:1.27.4-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
  lgtm-public:
    external: true
